default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: callisto7
  password:

development:
  <<: *default
  database: news_blog_dev

test:
  <<: *default
  database: news_blog_test

production:
  <<: *default
  database: news_blog_prod